### ISSUE TITLE
[BUG] Chrome Extention

### ISSUE THREAD

**Issue by mrmmg** [thedevs-network/kutt-extension#95]
Hi, the last kuttit chrome extension **doesn't add `https://`** in the first of link and when I share the link anybody must copy and paste it into the browser and the **link is not touchable**.

for example in discord:
[see this image](https://bit.ly/32yTPeq)

please fix this issue.
**Thanks, MMG**

**Comment by abhijithvijayan** [comment]
Duplicate of #94

**Comment by abhijithvijayan** [comment]
Thanks @mrmmg for the issue.

This was brought earlier to notice in #94 and was fixed in `v4.2.0`

I have fixed the issue and released a new version a couple of days ago.
The store version, by kutt author's information, will be up on the stores soon.

Sorry for the inconvenience caused with the major release.

**Comment by mrmmg** [comment]
Nice, Thanks you

**Comment by abhijithvijayan** [comment]
Feel free to rate on stores about the new release. :smile:

**Comment by abhijithvijayan** [comment]
@mrmmg Updated on stores.
